### ISSUE TITLE
No output from openmm-plumed

### ISSUE THREAD

**Issue by ruibinl** [peastman/openmm-plumed#15]
Hello everyone,
     I am new to the openmm-plumed plugin. I recently compiled openmm with plumed following the instructions. The compilation was successful and the openmm simulation can be run with 'PlumedForce' added to the system without complaining any error. I passed all tests for both plugin and the openmm from 'make test' command.  However, I don't see any effect of the plumed bias in my simulation, and there is no output of any PLUMED file. Changing the plumed 'script' string in the openmm input  has no effect on the simulation. I am not sure if I get my openmm input script right or not. The input script is attached below
     I compiled  OPENMM 7.2.1 with Plumed 2.4.1, with CUDA 8.0.44, swig 3.0.12. Any help will be greatly appreciated. 
Best wishes,
Ruibin

openmm input:

from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
from parmed import load_file
from openmmplumed import *

#prmtop = app.AmberPrmtopFile('KS_A.prmtop')
inpcrd = app.AmberInpcrdFile('mini.rst7')
prmtop = load_file('chr.prmtop', 'mini.rst7')

system = prmtop.createSystem(nonbondedMethod=app.PME,removeCMMotion=True, 
    nonbondedCutoff=1.2*unit.nanometers, rigidWater=False, 
    ewaldErrorTolerance=0.0005)

fc_ldih = 1000.0
dihresMEMB = mm.openmm.CustomTorsionForce('fc_ldih*max(0, abs(diff+wrap) - rwidth)^2; \
                                 wrap = 2*pi*(step(-diff-pi)-step(diff-pi)); \
                                 diff = theta - rtheta0; \
                                 rtheta0 = theta0*pi/180; \
                                 rwidth = width*pi/180;')
dihresMEMB.addGlobalParameter('fc_ldih', fc_ldih)
dihresMEMB.addGlobalParameter('pi', 3.141592653589793)
dihresMEMB.addPerTorsionParameter('width')
dihresMEMB.addPerTorsionParameter('theta0')
for line in open('dihe.txt', 'r'):
    segments = line.strip().split()
    atom1  = int(segments[0])
    atom2  = int(segments[1])
    atom3  = int(segments[2])
    atom4  = int(segments[3])
    theta0 = float(segments[4])
    width  = float(segments[5])
    dihresMEMB.addTorsion(atom1,atom2,atom3,atom4,[width,theta0])
system.addForce(dihresMEMB)

integrator = mm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 
    0.001*unit.picoseconds)
integrator.setConstraintTolerance(0.00001)

platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}

print('NPT Forces')
system.addForce(mm.MonteCarloMembraneBarostat(1*unit.bar, 0*unit.bar*unit.nanometers, 300*unit.kelvin, mm.MonteCarloMembraneBarostat.XYIsotropic, mm.MonteCarloMembraneBarostat.ZFree, 100))

simulation = app.Simulation(prmtop.topology, system, integrator, platform,properties)

print('Load Checkpoint')
simulation.loadCheckpoint('checkpoint_npt_r_2.chk')

script = "UNITS LENGTH=A TIME=fs ENERGY=kcal/mol\nd: DISTANCE ATOMS=3471,1463\nus: RESTRAINT ARG=d KAPPA=100 AT=10\nFLUSH STRIDE=10\nPRINT STRIDE=10 ARG=d,us.bias FILE=COLVAR"

plmd = PlumedForce(script)
system.addForce( plmd )

print('Restrained NPT Dynamics with membrane barostat')
simulation.reporters.append(app.DCDReporter('trajectory.dcd', 10))
simulation.reporters.append(app.StateDataReporter('results.dat', 10, step=True,
    potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True,
    volume=True,separator='\t'))
simulation.reporters.append(app.CheckpointReporter('checkpoint.chk', 10))
simulation.step(2000)
print('Done!')

**Comment by peastman** [comment]
Did you intend to close this and delete the description?  I take it you figured out the problem?

**Comment by ruibinl** [comment]
Yes, I figured it out. Thanks for asking.
