### ISSUE TITLE
Continuation line in PLUMED input

### ISSUE THREAD

**Issue by gitkol** [peastman/openmm-plumed#19]
I noticed that PLUMED had a limit to the input line length (if the line is too long, PLUMED seems to simply ignore that action). Of course, it is nice to split certain input lines anyhow, but while PLUMED itself has the ellipse syntax to create continuation lines, the OpenMM plugin doesn't seem to have this option. The ellipse is rejected by unknown keyword '...'. Is there a way to have continuation lines within the triple """ quotes? Thanks, Istvan

**Comment by peastman** [comment]
That seems to be a feature of PLUMED's file parser.  OpenMM just treats it as a series of lines and passes each one to `plumed_cmd()`.  In principle it could look for an ellipsis and merge lines together, but would that just cause PLUMED to ignore everything beyond its maximum line length?

**Comment by gitkol** [comment]
Thanks, Peter. I see, that means PLUMED is receiving/interpreting input lines from OpenMM one line at a time. Then, as you say pasting together lines within a pair of ellipses wouldn't help. I'll just have to keep the lines as short as possible. Unfortunately, sometimes I have a long list of CA atoms that I have to wrap or center around and I don't know of any concise way to list them. I may have to define multiple groups and then apply the action on the groups rather than on the whole atom list. -Istvan

**Comment by peastman** [comment]
Perhaps contact the PLUMED developers about this?  I don't know any reason it should be setting a limit on how long the lines can be.  We're a little beyond the punch card era. :)

**Comment by gitkol** [comment]
:) I did contact Max Bonomi. Will update this ticket if I hear back from him.

**Comment by gitkol** [comment]
After consulting with Max it turns out that my concern was a red herring. PLUMED does not limit the length of input lines, the problem had to do with TAB characters present in a pdb file that PLUMED misread, but that's another story. :) PLUMED is a really powerful tool with OpenMM. -Istvan
