### ISSUE TITLE
PLUMED forces with MTSIntegrator

### ISSUE THREAD

**Issue by gitkol** [peastman/openmm-plumed#22]
Hi, this is not strictly an issue but more of a question and/or feature request. The gist of the problem is that since PLUMED is running on CPU, it is a huge bottleneck and can slow down OpenMM-PLUMED simulations by multiple fold with respect to a pure OpenMM GPU simulation. PLUMED has a built-in STRIDE option that works for some actions such as METAD but not others like DRR. The basic idea behind STRIDE is to compute PLUMED forces only every so often instead of at every time step, but when computed, PLUMED forces are multiplied by the value of STRIDE. So, for example with STRIDE=2, PLUMED forces are computed only at every other time step but then the forces are multiplied by two, and this should work well for slow varying biases.

I was wondering if I can reproduce the same behavior using MTSIntegrator for any kind of PLUMED action. Normally I use MTSIntegrator like this:
integrator = MTSIntegrator(2*femptoseconds, [(2,1), (1,1), (0,2)])
where force group 1 is the nonbonded.setReciprocalSpaceForceGroup and group 2 is the PLUMED force. So, I could do something like this:
integrator = MTSIntegrator(4*femptoseconds, [(2,1), (1,2), (0,4)])

However, I don't fully understand how MTSIntegrator works. It is clear that the 3 different force groups are evaluated with different frequencies (and accordingly I do get a significant speed up applying the second integrator with respect to using the first integrator), but what exact forces are injected at intermediate time steps? I see 3 different options, but I couldn't figure out which if any is used in MTSIntegrator. Option 1) only forces that are computed are injected. Option 2) at intermediate steps the computed force(s) + a stale force (the last computed force) is injected for the remainder of the force group(s). Option 3) like option 1) but group 1 forces are multiplied by 2 and group 2 forces are multiplied by 4 when they are injected.

I can easily be wrong regarding all these options, could you clarify what MTSIntegrator does and whether what I suggest regarding PLUMED forces is feasible to do.

Thanks!

   Istvan

**Comment by peastman** [comment]
MTSIntegrator uses the rRESPA algorithm, which is based on a formal decomposition of the propagator.  Here's a way to think about it.  First simulate a few steps for a system that includes only the fast changing forces.  Hopefully those forces are fast to compute, so this doesn't take long.  But of course it isn't the result you want, since it omits some forces.  So now integrate the difference between that approximate system and the true system you're trying to simulate.  Since that difference depends only on the slow changing forces, you can integrate it with a larger time step.

Here's the paper that describes the algorithm: https://doi.org/10.1063/1.463137

**Comment by gitkol** [comment]
Got it. Thank you, Peter. It looks like there is no efficient way to inject
a multiple of the PLUMED force, then.

   Istvan

**Comment by peastman** [comment]
> It looks like there is no efficient way to inject a multiple of the PLUMED force, then.

In what sense?  This is exactly the sort of thing MTSIntegrator was created for.  Any reason it wouldn't work in this case?

**Comment by gitkol** [comment]
Sorry, what I meant was that instead of injecting PLUMED forces, say, every
2 time steps, I'd like to inject the PLUMED forces every 4 time steps, but
multiply them by 2.

**Comment by peastman** [comment]
Why?  That isn't a very accurate way of doing multiple timestep integration.  MTSIntegrator accomplishes the same purpose, but using a much more accurate algorithm.

**Comment by gitkol** [comment]
Agreed. My concern is trying to minimize the function calls to PLUMED since
it slows down the overall simulation speed tremendously, but you are right,
what I suggest is too rudimentary. Since the PLUMED biasing force only
affects a small number of atoms directly, I thought I could get away with
something like this, but probably not. PLUMED offers this approximate,
grain coursed biasing internally (so I asume it should work at least in
some cases), but not for the action I am using.

**Comment by gitkol** [comment]
course grained :)

**Comment by peastman** [comment]
What about the solution you suggested in your original post, using MTSIntegrator and having it only evaluate the PlumedForce every 2 or 4 steps.  Does that not meet all your needs?

**Comment by gitkol** [comment]
Hi Peter,

Thanks for the link, I read the paper and it seems it is my option 1) that
is happening in rRESPA. So, with a (1, 2) schedule short range forces are
computed and injected at every time step whereas at every other time step
in addition to the short range forces, long range forces are computed and
injected. Now, regarding PLUMED forces, let's assume for sake of argument
that the biasing force is very slowly changing, almost constant and
therefore similar to long range forces I can compute/inject them at their
own pace, say with a schedule of (1,2,4). However, the biasing force is
cumulative. With the long range force, it is perfectly fine to use a (1,1)
schedule, it'll be a tiny bit more accurate but much slower, and the
dynamics should be comparable with that of the (1, 2) schedule. The (very)
slowly changing/constant biasing force is different, if I halve the
frequency of injecting bias (going from schedule (1, 2, 2) to (1, 2, 4)) I
want to inject twice the bias, otherwise altogether my bias is only half of
what I need. If computing the bias is expensive (which is the case since
PLUMED is running on CPU) but it is slowly changing, I may want to use a
schedule, say, (1, 2, 8) or even (1, 2, 16), but then inject 4 times or 8
times the bias. Of course, there is a limit to this and I may as well ruin
the simulation, but the PLUMED documentation states that this is feasible,
and it would be nice to try it. As I mentioned before the built-in PLUMED
scheduling does not work for every action, and I don't see how I can inject
a multiple of a force with MTSIntegrator. If the OpenMM-PLUMED plugin could
multiply the PLUMED forces with a constant factor, that might do the trick.
I hope I was able to explain my problem.

Thanks,

   Istvan

**Comment by peastman** [comment]
MTSIntegrator takes care of all of this automatically.  Don't think of it as scaling forces.  It just integrates different subsets of forces with different time steps.  It multiplies each force by an appropriate dt.

Be aware that MTS algorithms are susceptible to resonance effects which limit their slowest time step.  Generally speaking, you want to keep it to less than half the period of the fastest motion in the system.  For typical molecular systems, that usually means no more than about 5 fs.

**Comment by gitkol** [comment]
That sounds great! I didn't realize MTS internally took care of that, this
is very good news.

Thanks a million,

   Istvan
