### ISSUE TITLE
Plumed api version mismatch

### ISSUE THREAD

**Issue by mpharrigan** [peastman/openmm-plumed#4]
With plumed 2.2.3

I get
`Exception: Unsupported API version.  Upgrade PLUMED to a newer version.`

The dev docs say it should be "2"
https://plumed.github.io/doc-v2.3/developer-doc/html/_how_to_plumed_your_m_d.html

But the check is for 4
https://github.com/peastman/openmm-plumed/blob/master/platforms/cuda/src/CudaPlumedKernels.cpp#L139

**Comment by mpharrigan** [comment]
Looks like the docs are wrong. The latest released version sets it to 3, the master branch is set to 4. Trying it now with master branch of plumed

**Comment by mpharrigan** [comment]
It works with the master of plumed. Maybe we can document this somewhere

**Comment by peastman** [comment]
It's been almost a year since I wrote that code.  Has there really not been a Plumed release since then?

**Comment by mpharrigan** [comment]
On Jun 30, they released 2.2.3 and 2.3b

2.2.3, api version 3
https://github.com/plumed/plumed2/blob/v2.2.3/src/core/PlumedMain.cpp#L307 

2.3b, api version 4
https://github.com/plumed/plumed2/blob/v2.3b/src/core/PlumedMain.cpp#L278

So it's released, but in beta
> Release 2.3b is a brand new release that contains a number of new features. Notice that some of the changes required us to modify the syntax of some command. See: http://goo.gl/iJl9BG  This release is still in beta, but we invite users to try it and provide feedbacks.
