### ISSUE TITLE
fatal error: openmm/Context.h

### ISSUE THREAD

**Issue by juanmit** [peastman/openmm-plumed#9]
Hi Peter,
I am trying to install the plugin on my workstation.  I already have the openmm7.0.1 installed using conda, and plumed installed separately. 
However, I always have a fatal error that says "fatal error: openmm/Context.h No such file or directory".

In the configuration file from ccmake,  I have tried 
~/anaconda/pkgs/openmm-7.0.1-py27_0/include
~/anaconda/pkgs/openmm-7.0.1-py27_0/include/openmm.

And I can see the Context.h file there.    Any ideas why?   Should I install openMM myself instead of using conda?   Thanks a lot for helping.

--Hongbin

**Comment by peastman** [comment]
What did you set OPENMM_DIR to when you ran CMake?  That's how it knows where to find the headers.

**Comment by juanmit** [comment]
I set it up like 

/home/hongbin/anaconda/pkgs/openmm-7.0.1-py27_0/include/openmm

and I can see the Context.h file there. 

--Hongbin

**Comment by peastman** [comment]
Set it to `/home/hongbin/anaconda/pkgs/openmm-7.0.1-py27_0`.  It wants the top level directory where OpenMM is installed.

By the way, the latest version of OpenMM is 7.1.1.  I'd definitely recommend upgrading.

**Comment by juanmit** [comment]
The Path works now.  Thanks a lot for helping. 
I upgraded the openmm as while.  :)

--Hongbin
